### ISSUE TITLE
Fedora Packaging

### ISSUE THREAD

**Issue by sudoprime** [sargon/trayer-srg#10]
Hi there, I just wanted to let you know that I have packaged trayer-srg into Fedora and I am working on pushing it into the Fedora repos. 

The bugzilla request can be found here: https://bugzilla.redhat.com/show_bug.cgi?id=827101

Thought you should know,
Thanks for the great software!
Bryan

**Comment by robstewart57** [comment]
Hello @sudoprime .

See this thread:

https://github.com/sargon/trayer-srg/issues/25

The link to the repository for the trayer Fedora packaging is dead. Where should the trayer README now point to? Are you still maintaining the trayer-srg Fedora package?

**Comment by sudoprime** [comment]
looks like I never followed through with upstream on this and it was never accepted. i no longer use fedora, so you will need to repackage and submit if you want this included. cheers!

**Comment by sargon** [comment]
Just removed the fedora link from the readme...
