### ISSUE TITLE
ubuntu installation

### ISSUE THREAD

**Issue by justinabrahms** [sargon/trayer-srg#27]
For ubuntu, you'll need these two libraries for installation to work.
- libgtk2.0-dev
- libxmu-dev

**Comment by sargon** [comment]
On 05/02/2016 07:15 PM, Justin Abrahms wrote:
> For ubuntu, you'll need these two libraries for installation to work.
> 
>   * libgtk2.0-dev
>   * libxmu-dev
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/sargon/trayer-srg/issues/27>
> 
Do you mean installation of a binary or build the package from source?

**Comment by justinabrahms** [comment]
building it from source.

Side issue, I've actually stopped using this library, as it doesn't fix the issue I had w/ the original. If I resize my display (via `xrandr`), it doesn't properly recalculate. There seems to be no way to trigger it to update itself. that I can see.

**Comment by sargon** [comment]
Okay. I think this one is related to #26 which I hadn't time to address myself.

**Comment by sargon** [comment]
Seems #26 is solved. Maybe this one is fixed too, plz review.
