### ISSUE TITLE
trayer disappear with icone change

### ISSUE THREAD

**Issue by domichel** [sargon/trayer-srg#35]
Using fvwm and fvwm-crystal, trayer is working fine with the recipe it is run on its own, but with the recipe where it is swallowed into a FvwmButtons, it disappear at icon change.

The same config was working before. This get triggered by some system update it was a long time ago. I get exactly the same issue with trayer-srg and have no clue on how to solve it.

As example, in the default config of fvwm:

```
#Test (x stalonetray) *RightPanel: (120x20, Swallow(NoClose,UseOld) \
#    stalonetray 'Exec exec stalonetray --config \
#    "$[FVWM_DATADIR]/default-config/.stalonetrayrc"', Frame 0)
Test (x trayer) *RightPanel: (120x20, Swallow(NoClose,UseOld) trayer 'Exec exec trayer --SetDockType false --widthtype pixel --heighttype false --height 20 --width 120', Frame 0)
#Test (x stalonetray) PipeRead 'echo "*RightPanel: (120x$(($[vp.height]-225)), \
Test (x trayer) PipeRead 'echo "*RightPanel: (120x$(($[vp.height]-225)), \
    Top, Swallow FvwmIconMan \'Module FvwmIconMan\', Frame 0)"'
#Test (!x stalonetray) PipeRead 'echo "*RightPanel: (120x$(($[vp.height]-205)),\
Test (!x trayer) PipeRead 'echo "*RightPanel: (120x$(($[vp.height]-205)),\
    Top, Swallow FvwmIconMan \'Module FvwmIconMan\', Frame 0)"'
*RightPanel: (120x45, Swallow DateTime 'Module FvwmScript FvwmScript-DateTime',\
    Frame 0)
*RightPanel: (120x5, Frame 0)
```

If I launch hexchat, trayer move from its button to over the pager, when it should stay in place.
With fvwm-crystal, as example with the amiga recipe, it is worst because it disappear from the view point and is not visible in the screen anymore.

That on gentoo with fvwm-2.6.7.1 and fvwm-crystal from its svn repository.

**Comment by sargon** [comment]
I can only guess that the fvwmbuttons does something wrong, maybe this bug report is better placed at the fvwm project.
